"""Generate REFERENCE.md from the config models + command registry.

The README points readers here for the exhaustive config and commands
tables. Re-run after touching ``src/naarad/config.py`` or
``src/naarad/commands.py``::

    uv run python scripts/gen_reference.py

A pytest (``tests/test_reference_drift.py``) re-runs this and fails the
build if ``REFERENCE.md`` is out of sync.
"""
from __future__ import annotations

import inspect
import json
from pathlib import Path

from pydantic import BaseModel
from pydantic.fields import FieldInfo
from pydantic_core import PydanticUndefined

from naarad.commands import COMMAND_REFERENCE
from naarad.config import Config

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_PATH = REPO_ROOT / "REFERENCE.md"

HEADER = """\
# Reference

> Auto-generated by `scripts/gen_reference.py` from the pydantic config
> models and the command registry. Do not edit by hand — re-run the
> script instead.

"""


def _is_basemodel(annotation: object) -> bool:
    return inspect.isclass(annotation) and issubclass(annotation, BaseModel)


def _render_default(value: object) -> str:
    """Render a default value as it would appear in config.json."""
    if isinstance(value, str):
        return f"`{json.dumps(value)}`"
    if isinstance(value, bool):
        return f"`{json.dumps(value)}`"
    if isinstance(value, (int, float, list, dict)):
        return f"`{json.dumps(value)}`"
    return f"`{value!r}`"


def _walk(model_cls: type[BaseModel], prefix: str = "") -> list[tuple[str, str, str]]:
    rows: list[tuple[str, str, str]] = []
    for name, field in model_cls.model_fields.items():
        path = f"{prefix}{name}" if not prefix else f"{prefix}.{name}"
        annotation = field.annotation
        if _is_basemodel(annotation):
            rows.extend(_walk(annotation, path))
            continue
        rows.append((path, _format_field_default(field), field.description or ""))
    return rows


def _format_field_default(field: FieldInfo) -> str:
    if field.default is not PydanticUndefined:
        return _render_default(field.default)
    if field.default_factory is not None:
        try:
            return _render_default(field.default_factory())  # type: ignore[call-arg]
        except Exception:
            return "—"
    return "**required**"


def _render_config_table() -> str:
    rows = _walk(Config)
    lines = [
        "## Configuration",
        "",
        "Everything lives in `config.json` (gitignored). The example file",
        "`config.example.json` shows the full shape with example values.",
        "",
        "| Key | Default | Description |",
        "|-----|---------|-------------|",
    ]
    for path, default, description in rows:
        # Escape pipe in description for table integrity.
        safe = description.replace("|", r"\|")
        lines.append(f"| `{path}` | {default} | {safe} |")
    return "\n".join(lines) + "\n"


def _render_commands_table() -> str:
    lines = [
        "## Commands",
        "",
        "All commands are also surfaced in Telegram's `/` autocomplete menu",
        "(top-level only) and printed by `/help` inside the bot.",
        "",
        "| Command | Description |",
        "|---------|-------------|",
    ]
    for cmd in COMMAND_REFERENCE:
        usage = cmd.usage.replace("|", r"\|")
        desc = cmd.description.replace("|", r"\|")
        lines.append(f"| `{usage}` | {desc} |")
    lines.append("")
    lines.append(
        "You can also confirm water by tapping the **💧 Drank water** "
        "button on any reminder, or by replying to a reminder with anything."
    )
    return "\n".join(lines) + "\n"


def render() -> str:
    return HEADER + _render_config_table() + "\n" + _render_commands_table()


def main() -> None:
    OUT_PATH.write_text(render(), encoding="utf-8")
    print(f"wrote {OUT_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
